name: Auto-Merge Dependaot PRs
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          approve-only: true
          use-github-auto-merge: true
          merge-method: merge
